project:
  type: website
  output-dir: _site

website:
  title: "site"
  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - section: "Machine Learning"
        contents: "src/machine-learning/*"

format:
  html:
    page-layout: full
    toc: true