<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>attention – site</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f8d8a529df1833e16d77ea24e1d85dda.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../src/machine-learning/Attention.html">Machine Learning</a></li><li class="breadcrumb-item"><a href="../../src/machine-learning/Attention.html">Attention Is All You</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">site</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/machine-learning/Attention.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Attention Is All You</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../src/machine-learning/Attention Is All You Need.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abstract</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#attention-is-all-you" id="toc-attention-is-all-you" class="nav-link active" data-scroll-target="#attention-is-all-you">Attention Is All You</a>
  <ul class="collapse">
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">Abstract</a></li>
  </ul></li>
  <li><a href="#introduzione" id="toc-introduzione" class="nav-link" data-scroll-target="#introduzione">1. Introduzione</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">2. Background</a>
  <ul class="collapse">
  <li><a href="#self-attention" id="toc-self-attention" class="nav-link" data-scroll-target="#self-attention">Self-attention</a></li>
  </ul></li>
  <li><a href="#architettura-del-modello" id="toc-architettura-del-modello" class="nav-link" data-scroll-target="#architettura-del-modello">3. Architettura del modello</a>
  <ul class="collapse">
  <li><a href="#encoder-e-decoder" id="toc-encoder-e-decoder" class="nav-link" data-scroll-target="#encoder-e-decoder">3.1 Encoder e decoder</a>
  <ul class="collapse">
  <li><a href="#encoder" id="toc-encoder" class="nav-link" data-scroll-target="#encoder">Encoder</a></li>
  <li><a href="#decoder" id="toc-decoder" class="nav-link" data-scroll-target="#decoder">Decoder</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#attention" id="toc-attention" class="nav-link" data-scroll-target="#attention">3.2 Attention</a>
  <ul class="collapse">
  <li><a href="#scaled-dot-product-attention" id="toc-scaled-dot-product-attention" class="nav-link" data-scroll-target="#scaled-dot-product-attention">3.2.1 Scaled Dot-Product Attention</a>
  <ul class="collapse">
  <li><a href="#perché-dividere-per-sqrtd_k" id="toc-perché-dividere-per-sqrtd_k" class="nav-link" data-scroll-target="#perché-dividere-per-sqrtd_k">Perché dividere per <span class="math inline">\(\sqrt{d_k}\)</span>?</a></li>
  </ul></li>
  <li><a href="#multi-head-attention" id="toc-multi-head-attention" class="nav-link" data-scroll-target="#multi-head-attention">3.2.2 Multi-Head Attention</a></li>
  <li><a href="#utilizzi-dellattention-nel-transformer" id="toc-utilizzi-dellattention-nel-transformer" class="nav-link" data-scroll-target="#utilizzi-dellattention-nel-transformer">3.2.3 Utilizzi dell’attention nel Transformer</a>
  <ul class="collapse">
  <li><a href="#encoder-decoder-attention" id="toc-encoder-decoder-attention" class="nav-link" data-scroll-target="#encoder-decoder-attention">Encoder-decoder attention</a></li>
  <li><a href="#self-attention-dellencoder" id="toc-self-attention-dellencoder" class="nav-link" data-scroll-target="#self-attention-dellencoder">Self-attention dell’encoder</a></li>
  <li><a href="#masked-self-attention-del-decoder" id="toc-masked-self-attention-del-decoder" class="nav-link" data-scroll-target="#masked-self-attention-del-decoder">Masked self-attention del decoder</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#position-wise-feed-forward-networks" id="toc-position-wise-feed-forward-networks" class="nav-link" data-scroll-target="#position-wise-feed-forward-networks">3.3 Position-wise Feed-Forward Networks</a></li>
  <li><a href="#embedding-e-softmax" id="toc-embedding-e-softmax" class="nav-link" data-scroll-target="#embedding-e-softmax">3.4 Embedding e Softmax</a></li>
  <li><a href="#positional-encoding" id="toc-positional-encoding" class="nav-link" data-scroll-target="#positional-encoding">3.5 Positional Encoding</a>
  <ul class="collapse">
  <li><a href="#codifica-sinusoidale" id="toc-codifica-sinusoidale" class="nav-link" data-scroll-target="#codifica-sinusoidale">Codifica sinusoidale</a></li>
  </ul></li>
  <li><a href="#perché-utilizzare-la-self-attention" id="toc-perché-utilizzare-la-self-attention" class="nav-link" data-scroll-target="#perché-utilizzare-la-self-attention">4. Perché utilizzare la Self-Attention</a>
  <ul class="collapse">
  <li><a href="#tabella-1-confronto-tra-tipi-di-layer" id="toc-tabella-1-confronto-tra-tipi-di-layer" class="nav-link" data-scroll-target="#tabella-1-confronto-tra-tipi-di-layer">Tabella 1 — Confronto tra tipi di layer</a></li>
  <li><a href="#parallelizzazione" id="toc-parallelizzazione" class="nav-link" data-scroll-target="#parallelizzazione">Parallelizzazione</a></li>
  <li><a href="#complessità" id="toc-complessità" class="nav-link" data-scroll-target="#complessità">Complessità</a></li>
  <li><a href="#confronto-con-le-convoluzioni" id="toc-confronto-con-le-convoluzioni" class="nav-link" data-scroll-target="#confronto-con-le-convoluzioni">Confronto con le convoluzioni</a></li>
  <li><a href="#interpretabilità" id="toc-interpretabilità" class="nav-link" data-scroll-target="#interpretabilità">Interpretabilità</a></li>
  </ul></li>
  <li><a href="#training" id="toc-training" class="nav-link" data-scroll-target="#training">5. Training</a>
  <ul class="collapse">
  <li><a href="#dati-e-batching" id="toc-dati-e-batching" class="nav-link" data-scroll-target="#dati-e-batching">5.1 Dati e batching</a></li>
  <li><a href="#hardware-e-schedule" id="toc-hardware-e-schedule" class="nav-link" data-scroll-target="#hardware-e-schedule">5.2 Hardware e schedule</a></li>
  <li><a href="#ottimizzatore" id="toc-ottimizzatore" class="nav-link" data-scroll-target="#ottimizzatore">5.3 Ottimizzatore</a></li>
  </ul></li>
  <li><a href="#regolarizzazione" id="toc-regolarizzazione" class="nav-link" data-scroll-target="#regolarizzazione">5.4 Regolarizzazione</a>
  <ul class="collapse">
  <li><a href="#residual-dropout" id="toc-residual-dropout" class="nav-link" data-scroll-target="#residual-dropout">Residual Dropout</a></li>
  <li><a href="#label-smoothing" id="toc-label-smoothing" class="nav-link" data-scroll-target="#label-smoothing">Label Smoothing</a></li>
  </ul></li>
  <li><a href="#risultati" id="toc-risultati" class="nav-link" data-scroll-target="#risultati">6. Risultati</a>
  <ul class="collapse">
  <li><a href="#machine-translation" id="toc-machine-translation" class="nav-link" data-scroll-target="#machine-translation">6.1 Machine Translation</a>
  <ul class="collapse">
  <li><a href="#wmt-2014-english-to-german" id="toc-wmt-2014-english-to-german" class="nav-link" data-scroll-target="#wmt-2014-english-to-german">WMT 2014 English-to-German</a></li>
  <li><a href="#wmt-2014-english-to-french" id="toc-wmt-2014-english-to-french" class="nav-link" data-scroll-target="#wmt-2014-english-to-french">WMT 2014 English-to-French</a></li>
  </ul></li>
  <li><a href="#tabella-2-bleu-e-costo-di-training" id="toc-tabella-2-bleu-e-costo-di-training" class="nav-link" data-scroll-target="#tabella-2-bleu-e-costo-di-training">Tabella 2 — BLEU e costo di training</a></li>
  <li><a href="#inferenza" id="toc-inferenza" class="nav-link" data-scroll-target="#inferenza">Inferenza</a></li>
  </ul></li>
  <li><a href="#variazioni-del-modello" id="toc-variazioni-del-modello" class="nav-link" data-scroll-target="#variazioni-del-modello">6.2 Variazioni del modello</a>
  <ul class="collapse">
  <li><a href="#tabella-3-variazioni-dellarchitettura" id="toc-tabella-3-variazioni-dellarchitettura" class="nav-link" data-scroll-target="#tabella-3-variazioni-dellarchitettura">Tabella 3 — Variazioni dell’architettura</a></li>
  <li><a href="#numero-di-attention-head-righe-a" id="toc-numero-di-attention-head-righe-a" class="nav-link" data-scroll-target="#numero-di-attention-head-righe-a">Numero di attention head — righe (A)</a></li>
  <li><a href="#dimensione-delle-keys-righe-b" id="toc-dimensione-delle-keys-righe-b" class="nav-link" data-scroll-target="#dimensione-delle-keys-righe-b">Dimensione delle keys — righe (B)</a></li>
  <li><a href="#dimensione-del-modello-righe-c" id="toc-dimensione-del-modello-righe-c" class="nav-link" data-scroll-target="#dimensione-del-modello-righe-c">Dimensione del modello — righe (C)</a></li>
  <li><a href="#dropout-e-label-smoothing-righe-d" id="toc-dropout-e-label-smoothing-righe-d" class="nav-link" data-scroll-target="#dropout-e-label-smoothing-righe-d">Dropout e label smoothing — righe (D)</a></li>
  <li><a href="#positional-encoding-riga-e" id="toc-positional-encoding-riga-e" class="nav-link" data-scroll-target="#positional-encoding-riga-e">Positional encoding — riga (E)</a></li>
  </ul></li>
  <li><a href="#risultati-e-direzioni-future-dichiarate-nel-lavoro" id="toc-risultati-e-direzioni-future-dichiarate-nel-lavoro" class="nav-link" data-scroll-target="#risultati-e-direzioni-future-dichiarate-nel-lavoro">Risultati e direzioni future dichiarate nel lavoro</a></li>
  <li><a href="#riferimenti-bibliografici" id="toc-riferimenti-bibliografici" class="nav-link" data-scroll-target="#riferimenti-bibliografici">Riferimenti bibliografici</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../src/machine-learning/Attention.html">Machine Learning</a></li><li class="breadcrumb-item"><a href="../../src/machine-learning/Attention.html">Attention Is All You</a></li></ol></nav></header>




<section id="attention-is-all-you" class="level1">
<h1>Attention Is All You</h1>
<p>Il lavoro introduce il <strong>Transformer</strong>, un’architettura per la trasduzione di sequenze (<strong>sequence transduction</strong>) basata esclusivamente su meccanismi di <strong>attenzione (attention)</strong>, senza utilizzare né reti ricorrenti né convoluzioni.</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Prima del Transformer, i principali modelli per la trasduzione di sequenze erano costruiti con <strong>reti neurali ricorrenti (Recurrent Neural Networks, RNN)</strong> o <strong>reti neurali convoluzionali (Convolutional Neural Networks, CNN)</strong> organizzate secondo una struttura <strong>encoder-decoder</strong>. I sistemi migliori integravano inoltre un meccanismo di attenzione per collegare encoder e decoder.</p>
<p>Il Transformer elimina completamente ricorrenza e convoluzioni e utilizza soltanto meccanismi di attenzione. Questa scelta rende il modello molto più parallelizzabile durante l’addestramento e permette di ridurre significativamente i tempi di training.</p>
<p>Nei task di traduzione automatica (<strong>machine translation</strong>) WMT 2014:</p>
<ul>
<li>inglese <span class="math inline">\(\rightarrow\)</span> tedesco: il modello raggiunge <strong>28,4 BLEU</strong>, migliorando di oltre 2 punti BLEU rispetto ai precedenti migliori risultati, inclusi gli ensemble;</li>
<li>inglese <span class="math inline">\(\rightarrow\)</span> francese: raggiunge <strong>41,0 BLEU</strong> con un singolo modello, dopo circa <strong>3,5 giorni di training su 8 GPU</strong>.</li>
</ul>
</section>
</section>
<section id="introduzione" class="level1">
<h1>1. Introduzione</h1>
<p>Le RNN, e in particolare le <strong>Long Short-Term Memory (LSTM)</strong> e le <strong>Gated Recurrent Unit / gated recurrent neural networks</strong>, rappresentavano gli approcci principali per problemi di <strong>modellazione di sequenze (sequence modeling)</strong> e trasduzione, come il <strong>language modeling</strong> e la traduzione automatica.</p>
<p>Il problema fondamentale delle architetture ricorrenti deriva dalla loro natura sequenziale. A ogni posizione <span class="math inline">\(t\)</span>, lo stato nascosto <span class="math inline">\(h_t\)</span> dipende dallo stato precedente <span class="math inline">\(h_{t-1}\)</span> e dall’input corrispondente alla posizione corrente. Concettualmente:</p>
<p><span class="math inline">\(h_t = f(h_{t-1}, x_t)\)</span>.</p>
<p>Di conseguenza, <span class="math inline">\(h_t\)</span> non può essere calcolato prima di <span class="math inline">\(h_{t-1}\)</span>. Questa dipendenza impedisce la piena parallelizzazione delle operazioni appartenenti alla stessa sequenza durante il training.</p>
<p>Il problema diventa particolarmente importante per sequenze lunghe: la memoria disponibile limita anche il numero di esempi che possono essere elaborati contemporaneamente in un batch.</p>
<p>Tecniche come la fattorizzazione delle operazioni e la <strong>computazione condizionale (conditional computation)</strong> miglioravano l’efficienza, ma non eliminavano la dipendenza sequenziale fondamentale delle RNN.</p>
<p>I meccanismi di <strong>attenzione (attention mechanisms)</strong> avevano già mostrato la capacità di modellare dipendenze indipendentemente dalla distanza tra gli elementi della sequenza. Tuttavia, prima del Transformer erano generalmente utilizzati insieme a una rete ricorrente.</p>
<p>L’idea centrale del lavoro consiste quindi nel sostituire completamente la ricorrenza con l’attenzione. Il Transformer utilizza l’attenzione per stabilire direttamente dipendenze globali tra gli elementi dell’input e dell’output.</p>
<p>Questa architettura permette una parallelizzazione molto maggiore e, negli esperimenti originali, raggiunge risultati allo stato dell’arte nella traduzione dopo appena <strong>12 ore di training su 8 GPU NVIDIA P100</strong>.</p>
</section>
<section id="background" class="level1">
<h1>2. Background</h1>
<p>Anche architetture precedenti come <strong>Extended Neural GPU</strong>, <strong>ByteNet</strong> e <strong>ConvS2S</strong> cercavano di ridurre la quantità di computazione sequenziale. Questi modelli impiegavano CNN per calcolare in parallelo le rappresentazioni delle diverse posizioni.</p>
<p>Rimaneva però un problema relativo alla distanza tra due elementi della sequenza.</p>
<p>In ConvS2S, il numero di operazioni necessarie affinché due posizioni distanti possano interagire cresce linearmente con la loro distanza; in ByteNet cresce invece in maniera logaritmica. Percorsi computazionali più lunghi possono rendere più difficile l’apprendimento delle <strong>dipendenze a lungo raggio (long-range dependencies)</strong>.</p>
<p>Nel Transformer, grazie alla <strong>self-attention</strong>, qualsiasi posizione può interagire direttamente con qualsiasi altra posizione all’interno dello stesso layer. Il numero di operazioni sequenziali necessarie per mettere in relazione due posizioni diventa quindi costante.</p>
<p>Un possibile svantaggio consiste nell’aggregazione di informazioni provenienti da più posizioni attraverso una media pesata dall’attenzione. Il Transformer compensa questa perdita di risoluzione mediante la <strong>Multi-Head Attention</strong>.</p>
<section id="self-attention" class="level2">
<h2 class="anchored" data-anchor-id="self-attention">Self-attention</h2>
<p>La <strong>self-attention</strong>, chiamata anche <strong>intra-attention</strong>, mette in relazione diverse posizioni appartenenti alla stessa sequenza per costruirne una rappresentazione.</p>
<p>Era già stata utilizzata con successo in task quali:</p>
<ul>
<li>comprensione del testo (<strong>reading comprehension</strong>);</li>
<li>riassunto astrattivo (<strong>abstractive summarization</strong>);</li>
<li>inferenza o implicazione testuale (<strong>textual entailment</strong>);</li>
<li>apprendimento di rappresentazioni delle frasi indipendenti dal task.</li>
</ul>
<p>Le <strong>end-to-end memory networks</strong> utilizzavano inoltre un meccanismo ricorrente di attenzione e avevano mostrato buoni risultati nel question answering e nel language modeling.</p>
<p>La caratteristica distintiva del Transformer consiste nell’essere un modello di trasduzione basato <strong>interamente sulla self-attention</strong>, senza RNN allineate alle posizioni della sequenza e senza convoluzioni.</p>
</section>
</section>
<section id="architettura-del-modello" class="level1">
<h1>3. Architettura del modello</h1>
<p>La maggior parte dei modelli di trasduzione neurale utilizza una struttura <strong>encoder-decoder</strong>.</p>
<p>Data una sequenza di input</p>
<p><span class="math inline">\((x_1,\ldots,x_n)\)</span>,</p>
<p>l’encoder produce una sequenza di rappresentazioni continue</p>
<p><span class="math inline">\(z=(z_1,\ldots,z_n)\)</span>.</p>
<p>A partire da <span class="math inline">\(z\)</span>, il decoder genera la sequenza di output</p>
<p><span class="math inline">\((y_1,\ldots,y_m)\)</span></p>
<p>un simbolo alla volta.</p>
<p>Il decoder è <strong>autoregressivo (autoregressive)</strong>: durante la generazione del simbolo successivo utilizza anche i simboli già generati.</p>
<p>Il Transformer mantiene questa struttura generale, ma encoder e decoder vengono costruiti utilizzando principalmente:</p>
<ul>
<li>self-attention;</li>
<li>Multi-Head Attention;</li>
<li>reti feed-forward applicate indipendentemente a ogni posizione.</li>
</ul>
<p><img src="NIPS-2017-attention-is-all-you-need-Paper_images/_page_2_Figure_0.jpeg" class="img-fluid" style="width:30.0%"></p>
<p><strong>Figura 1 — Architettura del Transformer.</strong> La metà sinistra rappresenta l’encoder, mentre quella destra rappresenta il decoder.</p>
<section id="encoder-e-decoder" class="level2">
<h2 class="anchored" data-anchor-id="encoder-e-decoder">3.1 Encoder e decoder</h2>
<section id="encoder" class="level3">
<h3 class="anchored" data-anchor-id="encoder">Encoder</h3>
<p>L’encoder consiste in uno stack di <span class="math inline">\(N=6\)</span> layer identici.</p>
<p>Ogni layer contiene due sottolayer:</p>
<ol type="1">
<li><strong>Multi-Head Self-Attention</strong>;</li>
<li>rete <strong>feed-forward position-wise</strong>, completamente connessa.</li>
</ol>
<p>Attorno a ciascun sottolayer viene applicata una <strong>connessione residua (residual connection)</strong>, seguita da <strong>normalizzazione di layer (Layer Normalization)</strong>.</p>
<p>L’operazione complessiva è:</p>
<p><span class="math inline">\(\operatorname{LayerNorm}(x+\operatorname{Sublayer}(x))\)</span>,</p>
<p>dove <span class="math inline">\(\operatorname{Sublayer}(x)\)</span> rappresenta la trasformazione eseguita dal particolare sottolayer.</p>
<p>Per poter sommare direttamente l’ingresso <span class="math inline">\(x\)</span> e l’uscita del sottolayer, tutti i sottolayer e gli embedding producono vettori della stessa dimensionalità:</p>
<p><span class="math inline">\(d_{\text{model}}=512\)</span>.</p>
</section>
<section id="decoder" class="level3">
<h3 class="anchored" data-anchor-id="decoder">Decoder</h3>
<p>Anche il decoder contiene <span class="math inline">\(N=6\)</span> layer identici.</p>
<p>Ogni layer possiede però <strong>tre</strong> sottolayer:</p>
<ol type="1">
<li>Multi-Head Self-Attention sul decoder;</li>
<li>Multi-Head Attention sulle rappresentazioni prodotte dall’encoder;</li>
<li>rete feed-forward position-wise.</li>
</ol>
<p>Come nell’encoder, ciascun sottolayer utilizza connessioni residuali e Layer Normalization.</p>
<p>La self-attention del decoder viene inoltre modificata per impedire a una posizione di accedere alle posizioni future. Si utilizza quindi una <strong>maschera causale (causal mask)</strong>.</p>
<p>In combinazione con lo spostamento di una posizione degli embedding di output, questo garantisce che la predizione alla posizione <span class="math inline">\(i\)</span> possa dipendere solamente dagli output delle posizioni precedenti a <span class="math inline">\(i\)</span>.</p>
</section>
</section>
</section>
<section id="attention" class="level1">
<h1>3.2 Attention</h1>
<p>Una funzione di attenzione riceve:</p>
<ul>
<li>una <strong>query</strong>;</li>
<li>un insieme di <strong>keys</strong>;</li>
<li>i corrispondenti <strong>values</strong>.</li>
</ul>
<p>Query, keys, values e output sono rappresentati come vettori.</p>
<p>L’output viene calcolato come somma pesata dei values. Il peso assegnato a ciascun value dipende dalla compatibilità tra la query e la key corrispondente.</p>
<section id="scaled-dot-product-attention" class="level2">
<h2 class="anchored" data-anchor-id="scaled-dot-product-attention">3.2.1 Scaled Dot-Product Attention</h2>
<p>Il Transformer utilizza la <strong>Scaled Dot-Product Attention</strong>.</p>
<p>Le query e le keys hanno dimensionalità <span class="math inline">\(d_k\)</span>, mentre i values hanno dimensionalità <span class="math inline">\(d_v\)</span>.</p>
<p>Per una query <span class="math inline">\(q\)</span> e una key <span class="math inline">\(k\)</span>, viene inizialmente calcolato il prodotto scalare <span class="math inline">\(q\cdot k\)</span>. Il risultato viene poi diviso per <span class="math inline">\(\sqrt{d_k}\)</span> e trasformato mediante softmax.</p>
<p>In pratica, le query vengono raccolte nella matrice <span class="math inline">\(Q\)</span>, le keys nella matrice <span class="math inline">\(K\)</span> e i values nella matrice <span class="math inline">\(V\)</span>.</p>
<p>La funzione è:</p>
<p><span class="math display">\[
\operatorname{Attention}(Q,K,V)
=
\operatorname{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right)V
\]</span></p>
<p>Il prodotto <span class="math inline">\(QK^T\)</span> genera una matrice contenente i punteggi di compatibilità tra tutte le query e tutte le keys.</p>
<p>La divisione per <span class="math inline">\(\sqrt{d_k}\)</span> costituisce la principale differenza rispetto alla normale <strong>dot-product attention</strong>, detta anche <strong>multiplicative attention</strong>.</p>
<p>Un’altra tecnica nota è l’<strong>additive attention</strong>, nella quale la compatibilità viene calcolata tramite una rete feed-forward con un singolo hidden layer.</p>
<p>Dot-product attention e additive attention hanno una complessità teorica simile, ma la prima è più veloce e più efficiente in termini di memoria perché può sfruttare implementazioni altamente ottimizzate della moltiplicazione matriciale.</p>
<p><img src="NIPS-2017-attention-is-all-you-need-Paper_images/_page_3_Figure_1.jpeg" class="img-fluid" style="width:20.0%"> <img src="NIPS-2017-attention-is-all-you-need-Paper_images/_page_3_Figure_2.jpeg" class="img-fluid" style="width:20.0%"></p>
<p><strong>Figura 2 — A sinistra:</strong> Scaled Dot-Product Attention. <strong>A destra:</strong> Multi-Head Attention, costituita da più funzioni di attention eseguite in parallelo.</p>
<section id="perché-dividere-per-sqrtd_k" class="level3">
<h3 class="anchored" data-anchor-id="perché-dividere-per-sqrtd_k">Perché dividere per <span class="math inline">\(\sqrt{d_k}\)</span>?</h3>
<p>Quando <span class="math inline">\(d_k\)</span> aumenta, il prodotto scalare tra query e key tende ad assumere valori di modulo sempre maggiore.</p>
<p>Supponendo che le componenti di <span class="math inline">\(q\)</span> e <span class="math inline">\(k\)</span> siano variabili casuali indipendenti con media <span class="math inline">\(0\)</span> e varianza <span class="math inline">\(1\)</span>:</p>
<p><span class="math inline">\(q\cdot k=\sum_{i=1}^{d_k}q_i k_i\)</span>.</p>
<p>Il prodotto scalare ha:</p>
<ul>
<li>media <span class="math inline">\(0\)</span>;</li>
<li>varianza <span class="math inline">\(d_k\)</span>.</li>
</ul>
<p>La sua deviazione standard cresce quindi come <span class="math inline">\(\sqrt{d_k}\)</span>.</p>
<p>Valori molto grandi inviati alla softmax possono portarla nelle regioni di saturazione, dove i gradienti diventano estremamente piccoli. Il fattore <span class="math inline">\(1/\sqrt{d_k}\)</span> normalizza la scala dei prodotti scalari e riduce questo problema.</p>
</section>
</section>
<section id="multi-head-attention" class="level2">
<h2 class="anchored" data-anchor-id="multi-head-attention">3.2.2 Multi-Head Attention</h2>
<p>Invece di applicare una sola funzione di attention utilizzando direttamente query, keys e values con dimensionalità <span class="math inline">\(d_{\text{model}}\)</span>, il Transformer crea <span class="math inline">\(h\)</span> diverse proiezioni lineari apprese.</p>
<p>Per ogni testa (<strong>attention head</strong>) vengono ottenute:</p>
<ul>
<li>query di dimensione <span class="math inline">\(d_k\)</span>;</li>
<li>keys di dimensione <span class="math inline">\(d_k\)</span>;</li>
<li>values di dimensione <span class="math inline">\(d_v\)</span>.</li>
</ul>
<p>Ogni testa esegue autonomamente la Scaled Dot-Product Attention. Gli output delle diverse teste vengono poi concatenati e sottoposti a un’ulteriore trasformazione lineare.</p>
<p>Formalmente:</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{MultiHead}(Q,K,V)
&amp;=
\operatorname{Concat}(\operatorname{head}_1,\ldots,\operatorname{head}_h)W^O,\\
\operatorname{head}_i
&amp;=
\operatorname{Attention}(QW_i^Q,KW_i^K,VW_i^V).
\end{aligned}
\]</span></p>
<p>Le matrici di proiezione hanno dimensioni:</p>
<p><span class="math inline">\(W_i^Q\in\mathbb{R}^{d_{\text{model}}\times d_k}\)</span>,</p>
<p><span class="math inline">\(W_i^K\in\mathbb{R}^{d_{\text{model}}\times d_k}\)</span>,</p>
<p><span class="math inline">\(W_i^V\in\mathbb{R}^{d_{\text{model}}\times d_v}\)</span>,</p>
<p><span class="math inline">\(W^O\in\mathbb{R}^{hd_v\times d_{\text{model}}}\)</span>.</p>
<p>Nel Transformer base:</p>
<p><span class="math inline">\(h=8\)</span>,</p>
<p><span class="math inline">\(d_k=d_v=\frac{d_{\text{model}}}{h}=\frac{512}{8}=64\)</span>.</p>
<p>La Multi-Head Attention consente al modello di concentrarsi contemporaneamente su informazioni appartenenti a <strong>diversi sottospazi di rappresentazione</strong> e a differenti posizioni della sequenza.</p>
<p>Una singola testa, invece, tende a combinare queste informazioni in un’unica media pesata.</p>
<p>Poiché ogni testa opera su una dimensionalità ridotta, l’uso di otto teste non comporta un costo otto volte superiore: il costo totale rimane comparabile a quello di una singola attention head che operasse sull’intera dimensionalità <span class="math inline">\(d_{\text{model}}\)</span>.</p>
</section>
<section id="utilizzi-dellattention-nel-transformer" class="level2">
<h2 class="anchored" data-anchor-id="utilizzi-dellattention-nel-transformer">3.2.3 Utilizzi dell’attention nel Transformer</h2>
<p>Il Transformer utilizza la Multi-Head Attention in tre modi differenti.</p>
<section id="encoder-decoder-attention" class="level3">
<h3 class="anchored" data-anchor-id="encoder-decoder-attention">Encoder-decoder attention</h3>
<p>Le queries provengono dal layer precedente del decoder, mentre keys e values provengono dall’output dell’encoder.</p>
<p>In questo modo ogni posizione del decoder può accedere a <strong>tutte le posizioni della sequenza di input</strong>.</p>
</section>
<section id="self-attention-dellencoder" class="level3">
<h3 class="anchored" data-anchor-id="self-attention-dellencoder">Self-attention dell’encoder</h3>
<p>Queries, keys e values derivano tutti dall’output del precedente layer dell’encoder.</p>
<p>Ogni posizione può quindi prestare attenzione a tutte le posizioni della rappresentazione prodotta dal layer precedente.</p>
</section>
<section id="masked-self-attention-del-decoder" class="level3">
<h3 class="anchored" data-anchor-id="masked-self-attention-del-decoder">Masked self-attention del decoder</h3>
<p>Anche nel decoder queries, keys e values derivano dalla stessa sequenza. Tuttavia, ogni posizione può accedere soltanto a se stessa e alle posizioni precedenti.</p>
<p>Le connessioni verso posizioni future vengono eliminate impostando a <span class="math inline">\(-\infty\)</span> i corrispondenti logit <strong>prima della softmax</strong>. Dopo la softmax, tali posizioni ricevono quindi peso pari a zero.</p>
<p>Questo procedimento, mostrato nella <strong>Figura 2</strong>, mantiene la proprietà autoregressiva del decoder.</p>
</section>
</section>
</section>
<section id="position-wise-feed-forward-networks" class="level1">
<h1>3.3 Position-wise Feed-Forward Networks</h1>
<p>Oltre ai sottolayer di attention, ogni layer dell’encoder e del decoder contiene una <strong>rete feed-forward position-wise (Position-wise Feed-Forward Network, FFN)</strong>.</p>
<p>La stessa rete viene applicata separatamente e in modo identico a ogni posizione della sequenza.</p>
<p>È composta da:</p>
<ol type="1">
<li>una trasformazione lineare;</li>
<li>un’attivazione ReLU;</li>
<li>una seconda trasformazione lineare.</li>
</ol>
<p>La funzione è:</p>
<p><span class="math display">\[
\operatorname{FFN}(x)
=
\max(0,xW_1+b_1)W_2+b_2
\]</span></p>
<p>Le matrici <span class="math inline">\(W_1,W_2\)</span> e i bias sono condivisi tra tutte le posizioni dello stesso layer, ma <strong>non</strong> tra layer differenti.</p>
<p>L’operazione può anche essere interpretata come due convoluzioni con kernel di dimensione <span class="math inline">\(1\)</span>.</p>
<p>Nel modello base:</p>
<p><span class="math inline">\(d_{\text{model}}=512\)</span>,</p>
<p>mentre la dimensionalità interna della FFN è:</p>
<p><span class="math inline">\(d_{\text{ff}}=2048\)</span>.</p>
<p>La struttura dimensionale è quindi:</p>
<p><span class="math inline">\(512 \rightarrow 2048 \rightarrow 512\)</span>.</p>
</section>
<section id="embedding-e-softmax" class="level1">
<h1>3.4 Embedding e Softmax</h1>
<p>Gli <strong>embedding appresi (learned embeddings)</strong> trasformano sia i token di input sia quelli precedentemente generati dal decoder in vettori di dimensionalità <span class="math inline">\(d_{\text{model}}\)</span>.</p>
<p>L’output finale del decoder viene invece convertito in una distribuzione di probabilità sul token successivo mediante:</p>
<ol type="1">
<li>una trasformazione lineare;</li>
<li>una funzione softmax.</li>
</ol>
<p>Il Transformer condivide la stessa matrice di pesi tra:</p>
<ul>
<li>embedding dell’encoder;</li>
<li>embedding del decoder;</li>
<li>trasformazione lineare precedente alla softmax finale.</li>
</ul>
<p>Si applica quindi <strong>weight sharing / weight tying</strong>.</p>
<p>Negli embedding, i pesi vengono inoltre moltiplicati per <span class="math inline">\(\sqrt{d_{\text{model}}}\)</span>.</p>
</section>
<section id="positional-encoding" class="level1">
<h1>3.5 Positional Encoding</h1>
<p>La self-attention, presa isolatamente, non contiene informazioni intrinseche sull’ordine degli elementi: senza un meccanismo aggiuntivo, una permutazione dei token produrrebbe una corrispondente permutazione delle rappresentazioni.</p>
<p>Poiché il Transformer non possiede né ricorrenza né convoluzioni, deve quindi aggiungere esplicitamente informazioni sulla posizione assoluta o relativa dei token.</p>
<p>A tale scopo utilizza le <strong>codifiche posizionali (positional encodings)</strong>.</p>
<p>Le positional encoding hanno la stessa dimensionalità degli embedding, cioè <span class="math inline">\(d_{\text{model}}\)</span>, e vengono <strong>sommate</strong> agli embedding all’ingresso dell’encoder e del decoder.</p>
<section id="codifica-sinusoidale" class="level2">
<h2 class="anchored" data-anchor-id="codifica-sinusoidale">Codifica sinusoidale</h2>
<p>Nel modello originale vengono utilizzate funzioni seno e coseno a frequenze differenti:</p>
<p><span class="math display">\[
\begin{aligned}
PE_{(pos,2i)}
&amp;=
\sin\left(\frac{pos}{10000^{2i/d_{\text{model}}}}\right),\\
PE_{(pos,2i+1)}
&amp;=
\cos\left(\frac{pos}{10000^{2i/d_{\text{model}}}}\right).
\end{aligned}
\]</span></p>
<p>Qui:</p>
<ul>
<li><span class="math inline">\(pos\)</span> indica la posizione del token;</li>
<li><span class="math inline">\(i\)</span> identifica la dimensione della rappresentazione.</li>
</ul>
<p>Ogni dimensione della positional encoding corrisponde quindi a una sinusoide con frequenza differente.</p>
<p>Le lunghezze d’onda seguono una progressione geometrica da <span class="math inline">\(2\pi\)</span> a <span class="math inline">\(10000\cdot2\pi\)</span>.</p>
<p>Gli autori scelgono questa forma perché, per un offset fisso <span class="math inline">\(k\)</span>, la rappresentazione <span class="math inline">\(PE_{pos+k}\)</span> può essere espressa come trasformazione lineare di <span class="math inline">\(PE_{pos}\)</span>. Ciò dovrebbe facilitare l’apprendimento di relazioni basate sulla <strong>posizione relativa</strong>.</p>
<p>Sono state sperimentate anche <strong>positional embedding apprese (learned positional embeddings)</strong>. I risultati risultano quasi identici a quelli delle codifiche sinusoidali, come mostrato nella <strong>Tabella 3, riga (E)</strong>.</p>
<p>Le sinusoidi vengono preferite perché potrebbero permettere al modello di generalizzare a sequenze più lunghe rispetto a quelle osservate durante il training.</p>
</section>
</section>
<section id="perché-utilizzare-la-self-attention" class="level1">
<h1>4. Perché utilizzare la Self-Attention</h1>
<p>Gli autori confrontano self-attention, ricorrenza e convoluzioni considerando la trasformazione di una sequenza</p>
<p><span class="math inline">\((x_1,\ldots,x_n)\)</span></p>
<p>in una nuova sequenza</p>
<p><span class="math inline">\((z_1,\ldots,z_n)\)</span>,</p>
<p>con <span class="math inline">\(x_i,z_i\in\mathbb{R}^d\)</span>.</p>
<p>Vengono utilizzati tre criteri:</p>
<ol type="1">
<li><strong>complessità computazionale per layer</strong>;</li>
<li>numero minimo di <strong>operazioni sequenziali</strong>, che determina il grado di parallelizzazione;</li>
<li><strong>lunghezza massima del percorso (maximum path length)</strong> tra due posizioni, rilevante per l’apprendimento delle dipendenze a lungo raggio.</li>
</ol>
<section id="tabella-1-confronto-tra-tipi-di-layer" class="level2">
<h2 class="anchored" data-anchor-id="tabella-1-confronto-tra-tipi-di-layer">Tabella 1 — Confronto tra tipi di layer</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 24%">
<col style="width: 25%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo di layer</th>
<th style="text-align: right;">Complessità per layer</th>
<th style="text-align: right;">Operazioni sequenziali</th>
<th style="text-align: right;">Maximum path length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Self-Attention</td>
<td style="text-align: right;"><span class="math inline">\(O(n^2d)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(1)\)</span></td>
</tr>
<tr class="even">
<td>Recurrent</td>
<td style="text-align: right;"><span class="math inline">\(O(nd^2)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(n)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(n)\)</span></td>
</tr>
<tr class="odd">
<td>Convolutional</td>
<td style="text-align: right;"><span class="math inline">\(O(knd^2)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(\log_k n)\)</span></td>
</tr>
<tr class="even">
<td>Restricted Self-Attention</td>
<td style="text-align: right;"><span class="math inline">\(O(rnd)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(1)\)</span></td>
<td style="text-align: right;"><span class="math inline">\(O(n/r)\)</span></td>
</tr>
</tbody>
</table>
<p>Nella <strong>Tabella 1</strong>, <span class="math inline">\(n\)</span> è la lunghezza della sequenza, <span class="math inline">\(d\)</span> la dimensionalità delle rappresentazioni, <span class="math inline">\(k\)</span> la dimensione del kernel convoluzionale e <span class="math inline">\(r\)</span> la dimensione del vicinato utilizzato nella restricted self-attention.</p>
</section>
<section id="parallelizzazione" class="level2">
<h2 class="anchored" data-anchor-id="parallelizzazione">Parallelizzazione</h2>
<p>Una RNN richiede <span class="math inline">\(O(n)\)</span> operazioni sequenziali, perché ciascuna posizione dipende dalla precedente.</p>
<p>La self-attention collega invece tutte le posizioni in un singolo layer e richiede soltanto <span class="math inline">\(O(1)\)</span> passaggi sequenziali rispetto alle posizioni. Le operazioni matriciali al suo interno possono essere eseguite in parallelo.</p>
</section>
<section id="complessità" class="level2">
<h2 class="anchored" data-anchor-id="complessità">Complessità</h2>
<p>La self-attention ha complessità: <span class="math inline">\(O(n^2d)\)</span>.</p>
<p>Una rete ricorrente ha invece: <span class="math inline">\(O(nd^2)\)</span>.</p>
<p>Pertanto la self-attention è computazionalmente più conveniente quando:</p>
<p><span class="math inline">\(n&lt;d\)</span>.</p>
<p>Secondo gli autori, questa condizione era generalmente soddisfatta nelle rappresentazioni di frasi utilizzate nei sistemi di traduzione dell’epoca, comprese le rappresentazioni <strong>word-piece</strong> e <strong>byte-pair</strong>.</p>
<p>Per sequenze estremamente lunghe, il termine quadratico <span class="math inline">\(n^2\)</span> può però diventare costoso.</p>
<p>Una possibile soluzione consiste nella <strong>restricted self-attention</strong>, nella quale ciascuna posizione presta attenzione soltanto a un vicinato di dimensione <span class="math inline">\(r\)</span>.</p>
<p>La complessità diventa:</p>
<p><span class="math inline">\(O(rnd)\)</span>,</p>
<p>ma la maximum path length aumenta a:</p>
<p><span class="math inline">\(O(n/r)\)</span>.</p>
</section>
<section id="confronto-con-le-convoluzioni" class="level2">
<h2 class="anchored" data-anchor-id="confronto-con-le-convoluzioni">Confronto con le convoluzioni</h2>
<p>Un singolo layer convoluzionale con kernel <span class="math inline">\(k&lt;n\)</span> non collega direttamente ogni coppia di posizioni.</p>
<p>Per consentire l’interazione tra posizioni distanti servono più layer:</p>
<ul>
<li><span class="math inline">\(O(n/k)\)</span> layer nel caso di kernel contigui;</li>
<li><span class="math inline">\(O(\log_k n)\)</span> nel caso di <strong>dilated convolutions</strong>.</li>
</ul>
<p>Questo aumenta la lunghezza del percorso che l’informazione deve attraversare.</p>
<p>Le normali convoluzioni hanno inoltre complessità <span class="math inline">\(O(knd^2)\)</span> e risultano generalmente più costose delle operazioni ricorrenti di un fattore legato a <span class="math inline">\(k\)</span>.</p>
<p>Le <strong>separable convolutions</strong> riducono la complessità a:</p>
<p><span class="math inline">\(O(knd+nd^2)\)</span>.</p>
<p>Anche ponendo <span class="math inline">\(k=n\)</span>, la loro complessità risulta comparabile alla combinazione adottata nel Transformer di self-attention e FFN position-wise.</p>
</section>
<section id="interpretabilità" class="level2">
<h2 class="anchored" data-anchor-id="interpretabilità">Interpretabilità</h2>
<p>Un ulteriore potenziale vantaggio della self-attention è una maggiore interpretabilità.</p>
<p>Analizzando le distribuzioni di attenzione, gli autori osservano che differenti attention head sembrano apprendere funzioni differenti e, in diversi casi, mostrano pattern collegabili alla struttura sintattica e semantica delle frasi.</p>
</section>
</section>
<section id="training" class="level1">
<h1>5. Training</h1>
<section id="dati-e-batching" class="level2">
<h2 class="anchored" data-anchor-id="dati-e-batching">5.1 Dati e batching</h2>
<p>Per la traduzione inglese <span class="math inline">\(\rightarrow\)</span> tedesco viene utilizzato il dataset <strong>WMT 2014 English-German</strong>, contenente circa <strong>4,5 milioni di coppie di frasi</strong>.</p>
<p>Le frasi vengono codificate mediante <strong>Byte-Pair Encoding (BPE)</strong> con un vocabolario condiviso tra source e target di circa <strong>37.000 token</strong>.</p>
<p>Per inglese <span class="math inline">\(\rightarrow\)</span> francese viene utilizzato il dataset <strong>WMT 2014 English-French</strong>, significativamente più grande, con circa <strong>36 milioni di coppie di frasi</strong> e un vocabolario <strong>word-piece</strong> di circa <strong>32.000 token</strong>.</p>
<p>Le coppie di frasi vengono raggruppate approssimativamente in base alla lunghezza.</p>
<p>Ogni training batch contiene circa:</p>
<ul>
<li>25.000 source token;</li>
<li>25.000 target token.</li>
</ul>
</section>
<section id="hardware-e-schedule" class="level2">
<h2 class="anchored" data-anchor-id="hardware-e-schedule">5.2 Hardware e schedule</h2>
<p>I modelli vengono addestrati su una singola macchina con <strong>8 GPU NVIDIA P100</strong>.</p>
<p>Per il <strong>Transformer base</strong>:</p>
<ul>
<li>circa <span class="math inline">\(0,4\)</span> secondi per training step;</li>
<li>100.000 step;</li>
<li>circa 12 ore di training.</li>
</ul>
<p>Per il <strong>Transformer big</strong>:</p>
<ul>
<li>circa <span class="math inline">\(1,0\)</span> secondo per step;</li>
<li>300.000 step;</li>
<li>circa 3,5 giorni di training.</li>
</ul>
</section>
<section id="ottimizzatore" class="level2">
<h2 class="anchored" data-anchor-id="ottimizzatore">5.3 Ottimizzatore</h2>
<p>Viene utilizzato l’ottimizzatore <strong>Adam</strong> con:</p>
<p><span class="math inline">\(\beta_1=0.9\)</span>,</p>
<p><span class="math inline">\(\beta_2=0.98\)</span>,</p>
<p><span class="math inline">\(\epsilon=10^{-9}\)</span>.</p>
<p>Il <strong>learning rate</strong> non rimane costante, ma viene modificato in funzione del numero di training step:</p>
<p><span class="math display">\[
\operatorname{lrate}
=
d_{\text{model}}^{-1/2}
\min\left(
\operatorname{step\_num}^{-1/2},
\operatorname{step\_num}\cdot
\operatorname{warmup\_steps}^{-3/2}
\right)
\]</span></p>
<p>con:</p>
<p><span class="math inline">\(\operatorname{warmup_steps}=4000\)</span>.</p>
<p>Durante i primi 4000 step, il learning rate cresce linearmente. Successivamente diminuisce in proporzione all’inverso della radice quadrata del numero di step:</p>
<p><span class="math inline">\(\operatorname{lrate}\propto\operatorname{step_num}^{-1/2}\)</span>.</p>
</section>
</section>
<section id="regolarizzazione" class="level1">
<h1>5.4 Regolarizzazione</h1>
<p>Gli autori utilizzano diverse tecniche di <strong>regolarizzazione (regularization)</strong>.</p>
<section id="residual-dropout" class="level2">
<h2 class="anchored" data-anchor-id="residual-dropout">Residual Dropout</h2>
<p>Il <strong>dropout</strong> viene applicato all’output di ciascun sottolayer prima della somma con la residual connection e della Layer Normalization.</p>
<p>Viene inoltre applicato alla somma tra embedding e positional encoding sia nell’encoder sia nel decoder.</p>
<p>Per il modello base:</p>
<p><span class="math inline">\(P_{\text{drop}}=0.1\)</span>.</p>
</section>
<section id="label-smoothing" class="level2">
<h2 class="anchored" data-anchor-id="label-smoothing">Label Smoothing</h2>
<p>Durante il training viene utilizzato <strong>label smoothing</strong> con:</p>
<p><span class="math inline">\(\epsilon_{ls}=0.1\)</span>.</p>
<p>Il label smoothing impedisce alla distribuzione target di essere completamente concentrata sulla classe corretta e rende quindi il modello meno sicuro nelle proprie predizioni.</p>
<p>Questo peggiora la <strong>perplexity</strong>, perché il modello assegna meno probabilità assoluta alla classe corretta, ma negli esperimenti migliora sia l’accuracy sia il punteggio BLEU.</p>
</section>
</section>
<section id="risultati" class="level1">
<h1>6. Risultati</h1>
<section id="machine-translation" class="level2">
<h2 class="anchored" data-anchor-id="machine-translation">6.1 Machine Translation</h2>
<section id="wmt-2014-english-to-german" class="level3">
<h3 class="anchored" data-anchor-id="wmt-2014-english-to-german">WMT 2014 English-to-German</h3>
<p>Il <strong>Transformer big</strong> ottiene:</p>
<p><span class="math inline">\(BLEU=28.4\)</span>.</p>
<p>Supera di oltre 2 punti BLEU i migliori risultati precedentemente riportati, compresi gli ensemble.</p>
<p>Il training richiede <strong>3,5 giorni su 8 GPU P100</strong>.</p>
<p>Anche il Transformer base supera i sistemi precedentemente pubblicati riportati nel confronto, con un costo computazionale di training molto inferiore.</p>
</section>
<section id="wmt-2014-english-to-french" class="level3">
<h3 class="anchored" data-anchor-id="wmt-2014-english-to-french">WMT 2014 English-to-French</h3>
<p>Il Transformer big raggiunge:</p>
<p><span class="math inline">\(BLEU=41.0\)</span>.</p>
<p>Il modello supera i precedenti risultati ottenuti da singoli modelli riportati nel lavoro con meno di un quarto del costo di training del precedente sistema single-model allo stato dell’arte.</p>
<p>Per questo esperimento il Transformer big utilizza:</p>
<p><span class="math inline">\(P_{\text{drop}}=0.1\)</span></p>
<p>anziché <span class="math inline">\(0.3\)</span>.</p>
</section>
</section>
<section id="tabella-2-bleu-e-costo-di-training" class="level2">
<h2 class="anchored" data-anchor-id="tabella-2-bleu-e-costo-di-training">Tabella 2 — BLEU e costo di training</h2>
<p>La <strong>Tabella 2</strong> confronta il Transformer con precedenti architetture sui test WMT 2014 English-German e English-French.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Modello</th>
<th style="text-align: right;">BLEU EN-DE</th>
<th style="text-align: right;">BLEU EN-FR</th>
<th style="text-align: right;">Training cost EN-DE</th>
<th style="text-align: right;">Training cost EN-FR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ByteNet</td>
<td style="text-align: right;">23.75</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Deep-Att + PosUnk</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">39.2</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;"><span class="math inline">\(1.0\times10^{20}\)</span> FLOPs</td>
</tr>
<tr class="odd">
<td>GNMT + RL</td>
<td style="text-align: right;">24.6</td>
<td style="text-align: right;">39.92</td>
<td style="text-align: right;"><span class="math inline">\(2.3\times10^{19}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.4\times10^{20}\)</span></td>
</tr>
<tr class="even">
<td>ConvS2S</td>
<td style="text-align: right;">25.16</td>
<td style="text-align: right;">40.46</td>
<td style="text-align: right;"><span class="math inline">\(9.6\times10^{18}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.5\times10^{20}\)</span></td>
</tr>
<tr class="odd">
<td>MoE</td>
<td style="text-align: right;">26.03</td>
<td style="text-align: right;">40.56</td>
<td style="text-align: right;"><span class="math inline">\(2.0\times10^{19}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.2\times10^{20}\)</span></td>
</tr>
<tr class="even">
<td>Deep-Att + PosUnk Ensemble</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">40.4</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;"><span class="math inline">\(8.0\times10^{20}\)</span></td>
</tr>
<tr class="odd">
<td>GNMT + RL Ensemble</td>
<td style="text-align: right;">26.30</td>
<td style="text-align: right;">41.16</td>
<td style="text-align: right;"><span class="math inline">\(1.8\times10^{20}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.1\times10^{21}\)</span></td>
</tr>
<tr class="even">
<td>ConvS2S Ensemble</td>
<td style="text-align: right;">26.36</td>
<td style="text-align: right;">41.29</td>
<td style="text-align: right;"><span class="math inline">\(7.7\times10^{19}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.2\times10^{21}\)</span></td>
</tr>
<tr class="odd">
<td>Transformer base</td>
<td style="text-align: right;">27.3</td>
<td style="text-align: right;">38.1</td>
<td style="text-align: right;"><span class="math inline">\(3.3\times10^{18}\)</span></td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Transformer big</td>
<td style="text-align: right;">28.4</td>
<td style="text-align: right;">41.0</td>
<td style="text-align: right;"><span class="math inline">\(2.3\times10^{19}\)</span></td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<p>Il costo viene stimato moltiplicando:</p>
<ul>
<li>durata del training;</li>
<li>numero di GPU;</li>
<li>capacità sostenuta stimata in operazioni floating-point a precisione singola di ciascuna GPU.</li>
</ul>
<p>Per questa stima vengono utilizzati valori di circa:</p>
<ul>
<li>K80: 2,8 TFLOPS;</li>
<li>K40: 3,7 TFLOPS;</li>
<li>M40: 6,0 TFLOPS;</li>
<li>P100: 9,5 TFLOPS.</li>
</ul>
</section>
<section id="inferenza" class="level2">
<h2 class="anchored" data-anchor-id="inferenza">Inferenza</h2>
<p>Per i modelli base viene utilizzato un singolo modello ottenuto mediando gli ultimi <strong>5 checkpoint</strong>, salvati a intervalli di 10 minuti.</p>
<p>Per i modelli big vengono mediati gli ultimi <strong>20 checkpoint</strong>.</p>
<p>La generazione utilizza <strong>beam search</strong> con:</p>
<ul>
<li>beam size <span class="math inline">\(=4\)</span>;</li>
<li>length penalty <span class="math inline">\(\alpha=0.6\)</span>.</li>
</ul>
<p>La lunghezza massima dell’output è impostata a:</p>
<p><span class="math inline">\(\text{lunghezza input}+50\)</span>,</p>
<p>con terminazione anticipata quando possibile.</p>
</section>
</section>
<section id="variazioni-del-modello" class="level1">
<h1>6.2 Variazioni del modello</h1>
<p>Per studiare l’importanza dei diversi componenti del Transformer, gli autori modificano sistematicamente il modello base e misurano le prestazioni sul development set <strong>newstest2013</strong> English-to-German.</p>
<p>In questi esperimenti viene utilizzata la beam search descritta precedentemente, ma senza checkpoint averaging.</p>
<section id="tabella-3-variazioni-dellarchitettura" class="level2">
<h2 class="anchored" data-anchor-id="tabella-3-variazioni-dellarchitettura">Tabella 3 — Variazioni dell’architettura</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 28%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Configurazione</th>
<th style="text-align: right;"><span class="math inline">\(N\)</span></th>
<th style="text-align: right;"><span class="math inline">\(d_{\text{model}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(d_{\text{ff}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(h\)</span></th>
<th style="text-align: right;"><span class="math inline">\(d_k\)</span></th>
<th style="text-align: right;"><span class="math inline">\(d_v\)</span></th>
<th style="text-align: right;"><span class="math inline">\(P_{\text{drop}}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\epsilon_{ls}\)</span></th>
<th style="text-align: right;">Step</th>
<th style="text-align: right;">PPL dev</th>
<th style="text-align: right;">BLEU dev</th>
<th style="text-align: right;">Parametri <span class="math inline">\(\times10^6\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>base</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">512</td>
<td style="text-align: right;">2048</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">64</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">100K</td>
<td style="text-align: right;">4.92</td>
<td style="text-align: right;">25.8</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td>(A)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">512</td>
<td style="text-align: right;">512</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.29</td>
<td style="text-align: right;">24.9</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">25.5</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">25.8</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.01</td>
<td style="text-align: right;">25.4</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>(B)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.16</td>
<td style="text-align: right;">25.1</td>
<td style="text-align: right;">58</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.01</td>
<td style="text-align: right;">25.4</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="even">
<td>(C)</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">6.11</td>
<td style="text-align: right;">23.7</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.19</td>
<td style="text-align: right;">25.3</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4.88</td>
<td style="text-align: right;">25.5</td>
<td style="text-align: right;">80</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.75</td>
<td style="text-align: right;">24.5</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1024</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4.66</td>
<td style="text-align: right;">26.0</td>
<td style="text-align: right;">168</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1024</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.12</td>
<td style="text-align: right;">25.4</td>
<td style="text-align: right;">53</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4096</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4.75</td>
<td style="text-align: right;">26.2</td>
<td style="text-align: right;">90</td>
</tr>
<tr class="odd">
<td>(D)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.77</td>
<td style="text-align: right;">24.6</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4.95</td>
<td style="text-align: right;">25.5</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">4.67</td>
<td style="text-align: right;">25.3</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">5.47</td>
<td style="text-align: right;">25.7</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>(E)</td>
<td style="text-align: right;">Positional embedding apprese al posto delle sinusoidi</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">4.92</td>
<td style="text-align: right;">25.7</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>big</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1024</td>
<td style="text-align: right;">4096</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">300K</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">26.4</td>
<td style="text-align: right;">213</td>
</tr>
</tbody>
</table>
<p>Le <strong>perplexity (PPL)</strong> riportate sono calcolate per word-piece sulla codifica BPE e non devono essere confrontate direttamente con perplexity per parola.</p>
</section>
<section id="numero-di-attention-head-righe-a" class="level2">
<h2 class="anchored" data-anchor-id="numero-di-attention-head-righe-a">Numero di attention head — righe (A)</h2>
<p>Mantenendo approssimativamente costante il costo computazionale, vengono modificati numero di attention head e dimensioni di keys e values.</p>
<p>Una singola testa ottiene <strong>0,9 BLEU in meno</strong> rispetto alla migliore configurazione considerata.</p>
<p>Anche utilizzare un numero eccessivamente elevato di teste riduce però la qualità: passare a 32 head, con <span class="math inline">\(d_k=d_v=16\)</span>, produce risultati inferiori alla configurazione base.</p>
<p>La scelta di più attention head rappresenta quindi un compromesso tra pluralità dei sottospazi rappresentativi e dimensionalità disponibile per ciascuna testa.</p>
</section>
<section id="dimensione-delle-keys-righe-b" class="level2">
<h2 class="anchored" data-anchor-id="dimensione-delle-keys-righe-b">Dimensione delle keys — righe (B)</h2>
<p>Ridurre <span class="math inline">\(d_k\)</span> peggiora le prestazioni.</p>
<p>Secondo gli autori, ciò suggerisce che calcolare correttamente la compatibilità tra query e key non sia un problema banale e lascia aperta la possibilità che funzioni di compatibilità più sofisticate del semplice prodotto scalare possano essere utili.</p>
</section>
<section id="dimensione-del-modello-righe-c" class="level2">
<h2 class="anchored" data-anchor-id="dimensione-del-modello-righe-c">Dimensione del modello — righe (C)</h2>
<p>Aumentare la capacità del modello tende a migliorare la qualità.</p>
<p>Per esempio, aumentando <span class="math inline">\(d_{\text{model}}\)</span> da <span class="math inline">\(512\)</span> a <span class="math inline">\(1024\)</span>, il BLEU di sviluppo passa da <span class="math inline">\(25.8\)</span> a <span class="math inline">\(26.0\)</span>, mentre aumentando <span class="math inline">\(d_{\text{ff}}\)</span> da <span class="math inline">\(2048\)</span> a <span class="math inline">\(4096\)</span> raggiunge <span class="math inline">\(26.2\)</span>.</p>
<p>Il miglioramento comporta però un aumento consistente del numero di parametri.</p>
<p>Il modello base contiene circa <strong>65 milioni di parametri</strong>, mentre il modello big ne contiene circa <strong>213 milioni</strong>.</p>
</section>
<section id="dropout-e-label-smoothing-righe-d" class="level2">
<h2 class="anchored" data-anchor-id="dropout-e-label-smoothing-righe-d">Dropout e label smoothing — righe (D)</h2>
<p>L’assenza di dropout porta a un netto peggioramento:</p>
<p><span class="math inline">\(BLEU=24.6\)</span></p>
<p>rispetto a:</p>
<p><span class="math inline">\(BLEU=25.8\)</span></p>
<p>del modello base.</p>
<p>Il risultato conferma l’importanza della regolarizzazione per limitare l’<strong>overfitting</strong>.</p>
<p>Anche il valore del label smoothing modifica il compromesso tra perplexity e BLEU.</p>
</section>
<section id="positional-encoding-riga-e" class="level2">
<h2 class="anchored" data-anchor-id="positional-encoding-riga-e">Positional encoding — riga (E)</h2>
<p>Sostituendo la positional encoding sinusoidale con <strong>positional embedding apprese</strong>, le prestazioni rimangono quasi identiche:</p>
<ul>
<li>modello base sinusoidale: BLEU <span class="math inline">\(25.8\)</span>;</li>
<li>positional embedding apprese: BLEU <span class="math inline">\(25.7\)</span>.</li>
</ul>
<p>Questo indica che, negli esperimenti effettuati, entrambe le strategie riescono a fornire efficacemente al modello l’informazione relativa alla posizione.</p>
</section>
</section>
<section id="risultati-e-direzioni-future-dichiarate-nel-lavoro" class="level1">
<h1>Risultati e direzioni future dichiarate nel lavoro</h1>
<p>Il Transformer viene presentato come il primo modello di sequence transduction basato interamente sull’attention, nel quale gli strati ricorrenti tipicamente presenti nelle architetture encoder-decoder vengono sostituiti dalla <strong>Multi-Head Self-Attention</strong>.</p>
<p>Nei task di traduzione considerati, il modello può essere addestrato significativamente più rapidamente rispetto alle architetture ricorrenti e convoluzionali confrontate nel lavoro.</p>
<p>Gli autori indicano inoltre diverse possibili estensioni:</p>
<ul>
<li>applicare modelli basati sull’attention a modalità differenti dal testo;</li>
<li>utilizzare il Transformer per immagini, audio e video;</li>
<li>studiare forme di <strong>local/restricted attention</strong> per gestire input e output molto lunghi in maniera più efficiente;</li>
<li>ridurre ulteriormente la natura sequenziale della fase di generazione.</li>
</ul>
<p>Il codice utilizzato per addestrare e valutare i modelli originali è stato reso disponibile attraverso il progetto <strong>Tensor2Tensor</strong>.</p>
</section>
<section id="riferimenti-bibliografici" class="level1">
<h1>Riferimenti bibliografici</h1>
<ol type="1">
<li>Jimmy Lei Ba, Jamie Ryan Kiros, Geoffrey E. Hinton, <em>Layer Normalization</em>, 2016.</li>
<li>Dzmitry Bahdanau, Kyunghyun Cho, Yoshua Bengio, <em>Neural Machine Translation by Jointly Learning to Align and Translate</em>, 2014.</li>
<li>Denny Britz, Anna Goldie, Minh-Thang Luong, Quoc V. Le, <em>Massive Exploration of Neural Machine Translation Architectures</em>, 2017.</li>
<li>Jianpeng Cheng, Li Dong, Mirella Lapata, <em>Long Short-Term Memory-Networks for Machine Reading</em>, 2016.</li>
<li>Kyunghyun Cho et al., <em>Learning Phrase Representations using RNN Encoder-Decoder for Statistical Machine Translation</em>, 2014.</li>
<li>François Chollet, <em>Xception: Deep Learning with Depthwise Separable Convolutions</em>, 2016.</li>
<li>Junyoung Chung et al., <em>Empirical Evaluation of Gated Recurrent Neural Networks on Sequence Modeling</em>, 2014.</li>
<li>Jonas Gehring et al., <em>Convolutional Sequence to Sequence Learning</em>, 2017.</li>
<li>Alex Graves, <em>Generating Sequences with Recurrent Neural Networks</em>, 2013.</li>
<li>Kaiming He et al., <em>Deep Residual Learning for Image Recognition</em>, 2016.</li>
<li>Sepp Hochreiter et al., <em>Gradient Flow in Recurrent Nets: The Difficulty of Learning Long-Term Dependencies</em>, 2001.</li>
<li>Sepp Hochreiter, Jürgen Schmidhuber, <em>Long Short-Term Memory</em>, 1997.</li>
<li>Rafal Jozefowicz et al., <em>Exploring the Limits of Language Modeling</em>, 2016.</li>
<li>Łukasz Kaiser, Ilya Sutskever, <em>Neural GPUs Learn Algorithms</em>, 2016.</li>
<li>Nal Kalchbrenner et al., <em>Neural Machine Translation in Linear Time</em>, 2017.</li>
<li>Yoon Kim et al., <em>Structured Attention Networks</em>, 2017.</li>
<li>Diederik Kingma, Jimmy Ba, <em>Adam: A Method for Stochastic Optimization</em>, 2015.</li>
<li>Oleksii Kuchaiev, Boris Ginsburg, <em>Factorization Tricks for LSTM Networks</em>, 2017.</li>
<li>Zhouhan Lin et al., <em>A Structured Self-Attentive Sentence Embedding</em>, 2017.</li>
<li>Samy Bengio, Łukasz Kaiser, <em>Can Active Memory Replace Attention?</em>, 2016.</li>
<li>Minh-Thang Luong, Hieu Pham, Christopher D. Manning, <em>Effective Approaches to Attention-Based Neural Machine Translation</em>, 2015.</li>
<li>Ankur Parikh et al., <em>A Decomposable Attention Model</em>, 2016.</li>
<li>Romain Paulus, Caiming Xiong, Richard Socher, <em>A Deep Reinforced Model for Abstractive Summarization</em>, 2017.</li>
<li>Ofir Press, Lior Wolf, <em>Using the Output Embedding to Improve Language Models</em>, 2016.</li>
<li>Rico Sennrich, Barry Haddow, Alexandra Birch, <em>Neural Machine Translation of Rare Words with Subword Units</em>, 2015.</li>
<li>Noam Shazeer et al., <em>Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer</em>, 2017.</li>
<li>Nitish Srivastava et al., <em>Dropout: A Simple Way to Prevent Neural Networks from Overfitting</em>, 2014.</li>
<li>Sainbayar Sukhbaatar et al., <em>End-to-End Memory Networks</em>, 2015.</li>
<li>Ilya Sutskever, Oriol Vinyals, Quoc V. Le, <em>Sequence to Sequence Learning with Neural Networks</em>, 2014.</li>
<li>Christian Szegedy et al., <em>Rethinking the Inception Architecture for Computer Vision</em>, 2015.</li>
<li>Yonghui Wu et al., <em>Google’s Neural Machine Translation System: Bridging the Gap Between Human and Machine Translation</em>, 2016.</li>
<li>Jie Zhou et al., <em>Deep Recurrent Models with Fast-Forward Connections for Neural Machine Translation</em>, 2016.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>